Repository Stackup-Rwanda/octopus-bn-frontend, pull requests merged in 2020-04, with the labels that each got.

#3 #172453017 Safely Shifting from Andela org to stackUP org(Badges)
  .coveralls.yml
  README.md
Labels: Done

#2 172430382-Deploying to Heroku
  package.json
Labels: Ready for Peer Review

#4 #170947379 user sign up
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/fileMock.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/__tests__/__snapshots__/login.spec.js.snap
  src/__tests__/index.spec.js
  src/__tests__/login.spec.js
  src/components/SignupForm.js
  src/components/SvgMap.js
  src/helpers/signuphelper.js
  src/index.js
  src/redux/actions/index.js
  src/redux/actions/signupAction.js
  src/redux/reducers/index.js
  src/redux/reducers/signupReducer.js
  src/redux/store.js
  src/redux/types/SignupTypes.js
  src/routes/index.js
  src/stories/App.stories.js
  src/styles/signup.module.css
  src/styles/styles.scss
  src/theme.js
  src/views/ConfirmEmail.js
  src/views/SignupPage.js
  webpack.config.js
Labels: Ready for Peer Review

#7 #172499577 Users should be able to switch between multiple languages
  package-lock.json
  package.json
  src/App.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/__tests__/__snapshots__/login.spec.js.snap
  src/__tests__/index.spec.js
  src/__tests__/login.spec.js
  src/components/LanguageButtons.js
  src/components/LoginForm.js
  src/components/SignupForm.js
  src/helpers/signuphelper.js
  src/index.js
  src/languages/components/IntlProvider.js
  src/languages/helper/processLocale.js
  src/languages/messages/en.json
  src/languages/messages/fr.json
  src/languages/messages/index.js
  src/languages/translate.js
  src/redux/actions/languageAction.js
  src/redux/actions/loginAction.js
  src/redux/reducers/index.js
  src/redux/reducers/languageReducer.js
  src/redux/store.js
  src/redux/types/languageTypes.js
  src/styles/entry.module.css
  src/styles/language.styles.module.css
  src/views/Dashboard.js
  src/views/Login.View.js
Labels: Ready for Peer Review

#8 #170947382 Users should be able to Login via Facebook and Google.
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/__tests__/__snapshots__/login.spec.js.snap
  src/__tests__/__snapshots__/lost.spec.js.snap
  src/__tests__/__snapshots__/social.buttons.spec.js.snap
  src/__tests__/__snapshots__/social.login.js.snap
  src/__tests__/language.spec.js
  src/__tests__/login.spec.js
  src/__tests__/lost.spec.js
  src/__tests__/social.buttons.spec.js
  src/__tests__/social.login.js
  src/components/LoginForm.js
  src/components/SignupForm.js
  src/components/SocialButtons.js
  src/components/SvgLost.js
  src/helpers/SocialLogin.js
  src/languages/messages/en.json
  src/languages/messages/fr.json
  src/routes/index.js
  src/styles/svg.lost.module.css
  src/views/Login.View.js
  src/views/Lost.View.js
  src/views/SignupPage.js
  webpack.config.js
Labels: Ready for TTL Review
